export const thirdValue = [
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
]
export const secondValue = [
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
]
export const firstValue = [
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
  {
    date: "05.05.22",
    title: "Hoodie NINJA",
    color: "RED",
    size: "S",
  },
]

export const initialValue = {
  date: "",
  title: "",
  color: "",
  size: "",
  quantity: "",
}

export const testValueArr = [{title: "firstValue", firstValue}, {title: "secondValue", secondValue}, {title: "thirdValue", thirdValue}];
